### ISSUE TITLE
US1 - (P02) [SP02] Cadastro de Usuários

### ISSUE THREAD

**Issue by rma98** [rma98/CIPA---CONCURSO-DE-IDEIAS-PROFESSOR-ANJO#1]
Como votante, eu gostaria de me cadastrar para poder acessar a página de votação do concurso de ideias.

**Comment by rma98** [comment]
Priorizando o primeiro US.1

**Comment by Andrielly091** [comment]
Professor @victorlira  veja se o código está correto e atendendo o que o senhor deseja para me colocar como concluída
